/**
 * Tokens copied verbatim from DESIGN.md YAML front-matter (FuMA Industrial).
 * Do not "improve" these values; they are the contract with the design system.
 */
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f2',
        'surface-dim': '#dcdad3',
        'surface-bright': '#FBFAF7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ec',
        'surface-container': '#f1eee7',
        'surface-container-high': '#ebe8e1',
        'surface-container-highest': '#e5e2db',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#55433c',
        'inverse-surface': '#31312c',
        'inverse-on-surface': '#f3f0e9',
        outline: '#88726b',
        'outline-variant': '#dbc1b8',
        'surface-tint': '#9a4523',
        primary: '#994422',
        'on-primary': '#ffffff',
        'primary-container': '#b85c38',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#ffb59a',
        secondary: '#5f5e5b',
        'on-secondary': '#ffffff',
        'secondary-container': '#e5e2de',
        'on-secondary-container': '#656461',
        tertiary: '#5b5f4d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#747865',
        'on-tertiary-container': '#ffffff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbcf',
        'primary-fixed-dim': '#ffb59a',
        'on-primary-fixed': '#380d00',
        'on-primary-fixed-variant': '#7b2f0e',
        'secondary-fixed': '#e5e2de',
        'secondary-fixed-dim': '#c9c6c2',
        'on-secondary-fixed': '#1c1c1a',
        'on-secondary-fixed-variant': '#474744',
        'tertiary-fixed': '#e1e5ce',
        'tertiary-fixed-dim': '#c5c9b3',
        'on-tertiary-fixed': '#191d0f',
        'on-tertiary-fixed-variant': '#454938',
        background: '#fcf9f2',
        'on-background': '#1c1c18',
        'surface-variant': '#e5e2db',
        'border-subtle': '#D8D2C8',
        'ink-graphite': '#34332F',
      },
      // Precision-Sharp shape language: 90-degree corners everywhere.
      // `full` survives only for the rare status dot.
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '32px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-gap': '128px',
      },
      fontFamily: {
        'display-hero': ['Instrument Serif', 'serif'],
        'headline-lg': ['Instrument Serif', 'serif'],
        'headline-lg-mobile': ['Instrument Serif', 'serif'],
        'headline-md': ['Instrument Serif', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'data-mono': ['IBM Plex Mono', 'monospace'],
        'label-caps': ['IBM Plex Mono', 'monospace'],
        annotation: ['IBM Plex Mono', 'monospace'],
      },
      fontSize: {
        'display-hero': ['96px', { lineHeight: '100px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg': ['64px', { lineHeight: '72px', fontWeight: '400' }],
        'headline-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        annotation: ['11px', { lineHeight: '14px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
